### PR TITLE
Added FactsUI and ProblemsUi to get project output

### PR DESCRIPTION
**Pull request by polinashtanko**
# Checklist
The PR https://github.com/uselagoon/lagoon-cli/pull/249 introduced the ability to directly set the factsUi and problemsUi fields for a project.

Added factsUi and problems Ui to lagoon-cli/pkg/lagoon/projects/main.go and  internal/lagoon/client/_lgraphql

# Changelog Entry

### CODE REVIEW

**Review by shreddedbacon — CHANGES_REQUESTED** [review]
All good, just one step missing which I will need to make note of in our contributing docs is that any changes to `x.graphql` files requires a `make gen` to be run, otherwise the auto generated code doesn't get updated.

Once you run `make gen` and push up the corrected auto generated code, this should be ready for :rocket:

**Comment by polinashtanko** [comment]
closes #252

**Review by shreddedbacon — APPROVED** [review]
:rocket:

**Comment by tobybellwood** [comment]
image

**Pull request merged**
