### PR TITLE
Feature: support add, list, update, and delete of deploytargets (kubernetes/openshift)

### PR DESCRIPTION
**Pull request by timclifford**
`go run main.go -l local add os -N os-1 -U "https://console-ch.amazeeio.test" -T "eyJhbGciOiJSUz..."`

`go run main.go -l local delete os -N os-1`

### CODE REVIEW

**Comment by shreddedbacon** [comment]
We should not use `openshift` naming here.

I would prefer to see `deploytarget` used in the CLI rather than using `kubernetes` or `openshift`.

The underlying graphql queries should use the `kubernetes` versions of the query/mutations as the openshift specific ones may disappear in the future, but as above, I'd like to see this phased out to be `deploytarget`

For consistency sake though, for this first round change everything to the `kubernetes` equivalents and remove any references to `openshift` (even on the existing add/update project commands)

**Review by shreddedbacon — CHANGES_REQUESTED** [review]
I'd actually like all the `openshift` references to be removed.

I'd much prefer it to be `deploytarget` but since the API doesn't really support this (except in deploytargetconfigs only), we should change all references from `openshift` to `kubernetes`

All of the openshift queries and mutations have kubernetes based alternatives that we should also use too. As I foresee the openshift ones being deprecated at some stage

Also, adding an `update` command would be handy. As well as any references to `openshifts` in the existing commands (i believe only add/update project support these at the moment)

**Comment by smlx** [comment]
@shreddedbacon we could just use `deploytarget` in the CLI and then eventually migrate the graphql over to the new API if/when it appears. I'm not sure what the policy of the `lagoon-cli` is on mirroring the Lagoon graphql API 1:1 is though.

**Comment by shreddedbacon** [comment]
> @shreddedbacon we could just use `deploytarget` in the CLI and then eventually migrate the graphql over to the new API if/when it appears. I'm not sure what the policy of the `lagoon-cli` is on mirroring the Lagoon graphql API 1:1 is though.

We haven't really got a policy on 1:1 mirroring the API, typically I've just made the decision autocratically, but this needs to change too.

I would much prefer we called it `deploytarget` in the CLI from the get go. 
Reason being, we support kubernetes and openshift/rosa currently, but what if some new deployment platform comes along in the future? We would need to create a bunch of new stuff in the future to support those other target. By going with deploytarget, we can somewhat futureproof.

I guess if we come to a consensus on what it should be in the CLI, then we can push for this change in core too?

**Comment by tobybellwood** [comment]
Happy to let the cli lead the terminology change - one consideration is that the addition of a `deployTarget` to openshift is conceptually different to the configuration of a `deployTarget` for a project, although a descendant.

Could we say targetCluster / remoteCluster / or similar for the actual addition of the lagoon-remote?

**Comment by tobybellwood** [comment]
Based on the code - the project configuration uses `DeployTargetConfig` - so using `DeployTarget` to refer to the underlying openshift/kubernetes makes sense.

**Pull request merged**
