### PR TITLE
Configure application security policy in CI

### PR DESCRIPTION
**Pull request by smlx**
Partially addresses #360.

Once this is merged, we can enable Dependabot at which point #360 can be closed.

### CODE REVIEW

**Comment by shreddedbacon** [comment]
I've address all the go lint complaints now. Will leave the action stuff for someone else to address.

**Comment by smlx** [comment]
If it is easier, this can be merged without the actions changes for now. None of the checks are required - just advisory. Then at a later stage once the issues are fixed the checks can be enforced.

**Comment by shreddedbacon** [comment]
> If it is easier, this can be merged without the actions changes for now. None of the checks are required - just advisory. Then at a later stage once the issues are fixed the checks can be enforced.

I think just the idea of it having a constant red failure that is an advisory will still irk me. I'm happy to wait a bit to see if someone else can address the actions stuff before it annoys me too much.

**Comment by tobybellwood** [comment]
I've disabled shellcheck on actions - it's very needy! We can always work on it in the background.

**Review by tobybellwood — APPROVED** [review]
Happy to get this in place - and tweak as may be necessary!

**Pull request merged**
