### PR TITLE
Refactor: Updates return types to utilize the output package

### PR DESCRIPTION
**Pull request by CGoodwin90**
Updates various commands to return zero results + relevant messaging, instead of returning an error when no results are found for a valid command.

Requires https://github.com/uselagoon/machinery/pull/43

Closes https://github.com/uselagoon/lagoon-cli/issues/318

### CODE REVIEW

**Comment by shreddedbacon** [comment]
Is this one still required?

**Comment by CGoodwin90** [comment]
Just disregard this one for now, need to go through and see if it's worth implementing

**Comment by shreddedbacon** [comment]
@CGoodwin90 can you fix this one up so it can be reviewed for merging today please :D

**Review by shreddedbacon — APPROVED** [review]
Good for now

**Pull request merged**
